version: '3.5'

volumes:
  portainer_data: {}

services:
  portainer:
    image:  portainer/portainer
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
